version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=12345

    ports:
      - 5050:80

  mysql: # THIS IS THE <<SERVICE_NAME>>
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_ROOT_PASSWORD=12345
      #- MYSQL_USER=
      #- PORT=3307

    ports:
      - 3307:3306

    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql #THE VALUE MUST BE THE <<SERVICE_NAME>> THAT IT'L BE CONNECTING WITH
      - MYSQL_ROOT_PASSWORD=12345

    ports:
      - 8080:80
