version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=12345

    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DB=my_store
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=12345
      - PORT=3306

    ports:
      - 3306:3306

    volumes:
      - ./mysql_data:/var/lib/mysql
